services:
  network-list-sync-main:
    container_name: network-list-sync
    hostname: network-list-sync
    extends:
      file: compose.base.yaml
      service: network-list-sync-base
    image: ghcr.io/mstrhakr/network-list-sync:main
    profiles: [main]

  network-list-sync-latest:
    container_name: network-list-sync
    hostname: network-list-sync
    extends:
      file: compose.base.yaml
      service: network-list-sync-base
    image: ghcr.io/mstrhakr/network-list-sync:latest
    profiles: [latest]

  network-list-sync-build:
    container_name: network-list-sync-build
    hostname: network-list-sync
    extends:
      file: compose.base.yaml
      service: network-list-sync-base
    build:
      context: .
      dockerfile: Dockerfile
    profiles: [build]

networks:
  backend:
    name: backend
    external: true